title: It definitely worked on my computer
description: >
  This blog contains wild-eyed rants and 
  things that I need to write down somewhere. 
  Obviously, the views expressed here are my own.
author: Stephen Hogg
email: saenet.r@gmail.com
show_excerpts: true # set to true to show excerpts on the homepage
header_pages: ['about.md']

theme: minima
plugins:
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-feed
relative_links:
  enabled: true
  collections: true

date_format: "%b %-d, %Y"
twitter_username: whistle_posse
github_username: StephenHogg
linkedin_username: stephen-hogg-80109372

defaults:
  scope:
    path: _drafts
  values:
    layout: post
    comments: false

collections:
  drafts:
    output: true
