author: Stephen Hogg
email: saenet.r@gmail.com
twitter: whistle_posse
show_excerpts: false # set to true to show excerpts on the homepage

theme: minima
plugins:
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-feed
relative_links:
  enabled: true
  collections: true

minima:
  date_format: "%b %-d, %Y"
  social_links:
    twitter: whistle_posse
    github: StephenHogg
