author: Stephen Hogg
email: saenet.r@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  Stuff that I thought of and want to write down goes here. Things I 
  need to remember go here, too. 
show_excerpts: false # set to true to show excerpts on the homepage

theme: jekyll-theme-slate
plugins:
  - jekyll-relative-links
  - jekyll-seo-tag
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
  - Transformers_part1.md
jekyll-theme-slate:
  social_links:
    twitter: whistle_posse
    github: StephenHogg
